[package]
name = "faint_locker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
libaes = "0.6.4"
rand = "0.8.5"
reqwest = { version = "0.11.14", features = ["json", "blocking"] }
